### PR TITLE
try to retry timed out hosts 3 times before marking down

### PR DESCRIPTION
**Pull request by riot-jayb**
i'm not super happy with how ugly this is. but timeouts could be on either side, so maybe worth retrying a couple times before marking down?

### CODE REVIEW

**Comment by kiryojo** [comment]
I'm not sure that retries are the right call here--I think it's incorrect that the hosts get marked as down in the first place.  I'd rather remove the entire marked down section than put in an additional hack on top of it.

**Comment by riot-jayb** [comment]
yes the markdown function is actually quite nice.

https://github.com/rdxsl/go-marathon/blob/master/cluster.go#L120

It starts a goroutine that will ping every 5 sec to return the host to the list.

Initially I wanted to kill the markDown() stuff but i really like the way it does healthchecks and its true that timeouts/500s might be good reasons to skip that host for 5sec.

**Comment by sizzlean** [comment]
As far as I can tell this member status is not publicly accessible anywhere. It'd be nice to expose it somehow so we can tell what the status of the cluster is and mark ourselves as degraded if the marathon masters are all down

**Comment by riot-jayb** [comment]
closing this for now because i'm not sure its needed

**Pull request closed without merging**
